export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILED = "SIGN_UP_FAILED";

export const SIGN_IN_REQUEST = "SIGN_IN_REQUEST";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAILED = "SIGN_IN_FAILED";
export const CHANGE_INFO = "CHANGE_INFO";

export const UPDATE_USER = "UPDATE_USER";
export const LOGOUT = "LOGOUT";
export const SELECTED = "SELECTED";

export const GET_SELECTED_ARTICLE_REQUEST = "GET_SELECTED_ARTICLE_REQUEST";
export const GET_SELECTED_ARTICLE_SUCCESS = "GET_SELECTED_ARTICLE_SUCCESS";
export const GET_SELECTED_ARTICLE_FAILED = "GET_SELECTED_ARTICLE_FAILED";

export const CHANGE_SELECT_DATE = "CHANGE_SELECT_DATA";

export const POST_ARTICLE_REQUEST = "POST_ARTICLE_REQUEST";
export const POST_ARTICLE_SUCCESS = "POST_ARTICLE_SUCCESS";
export const POST_ARTICLE_FAILED = "POST_ARTICLE_FAILED";

export const GET_ARTICLE_THIS_MONTH_REQUEST = "GET_ARTICLE_THIS_MONTH_REQUEST";
export const GET_ARTICLE_THIS_MONTH_SUCCESS = "GET_ARTICLE_THIS_MONTH_SUCCESS";
export const GET_ARTICLE_THIS_MONTH_FAILED = "GET_ARTICLE_THIS_MONTH_FAILED";

export const SEARCH_REQUEST = "SEARCH_REQUEST";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAILED = "SEARCH_FAILED";

export const FRIEND_REQUEST_REQUEST = "FRIEND_REQUEST_REQUEST";
export const FRIEND_REQUEST_SUCCESS = "FRIEND_REQUEST_SUCCESS";
export const FRIEND_REQUEST_FAILED = "FRIEND_REQUEST_FAILED";

export const GET_ARTICLE_REQUEST = "GET_ARTICLE_REQUEST";
export const GET_ARTICLE_SUCCESS = "GET_ARTICLE_SUCCESS";
export const GET_ARTICLE_FAILED = "GET_ARTICLE_FAILED";
export const GET_ARTICLE_RESET = "GET_ARTICLE_RESET";
export const GET_UPDATED_ARTICLE = "GET_UPDATED_ARTICLE";

export const POST_COMMENT_REQUEST = "POST_COMMENT_REQUEST";
export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS";
export const POST_COMMENT_FAILED = "POST_COMMENT_FAILED";

export const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS";
export const GET_UPDATED_COMMENT = "GET_UPDATED_COMMENT";
export const GET_COMMENT_FAILED = "GET_COMMENT_FAILED";
export const GET_COMMENT_RESET = "GET_COMMENT_RESET";

export const CREATE_GROUP_REQUEST = "CREATE_GROUP_REQUEST";
export const CREATE_GROUP_SUCCESS = "CREATE_GROUP_SUCCESS";
export const CREATE_GROUP_FAILED = "CREATE_GROUP_FAILED";

export const GET_ADMIN_GROUP_SUCCESS = "GET_ADMIN_GROUP_SUCCESS";
export const GET_NEW_ADMIN_GROUP_SUCCESS = "GET_NEW_ADMIN_GROUP_SUCCESS";

export const UPDATE_PRIVATE_ARTICLE_REQUEST = "UPDATE_ARTICLE_REQUEST";
export const UPDATE_PRIVATE_ARTICLE_FAILED = "UPDATE_ARTICLE_FAILED";
export const UPDATE_PRIVATE_ARTICLE_SUCCESS = "UPDATE_ARTICLE_SUCCESS";

export const DELETE_ARTICLE = "DELETE_ARTICLE";

export const GET_WHO_FOLLOW_ME_SUCCESS = "GET_WHO_FOLLOW_ME_SUCCESS";

export const SEND_MESSAGE_SUCCESS= "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAILED = "SEND_MESSAGE_FAILED";
export const SEND_MESSAGE_REQUEST = "SEND_MESSAGE_REQUEST";

export const GET_MESSAGE_SUCCESS= "GET_MESSAGE_SUCCESS";
export const GET_MESSAGE_FAILED = "GET_MESSAGE_FAILED";
export const GET_MESSAGE_REQUEST = "GET_MESSAGE_REQUEST";

export const GROUP_JOIN_REQUEST = "GROUP_JOIN_REQUEST";
export const GROUP_JOIN_SUCCESS = "GROUP_JOIN_SUCCESS";
export const GROUP_JOIN_FAILED = "GROUP_JOIN_FAILED";

export const SEARCH_GROUP_MEMBER_REQUEST = "SEARCH_GROUP_MEMBER_REQUEST";
export const SEARCH_GROUP_MEMBER_SUCCESS = "SEARCH_GROUP_MEMBER_SUCCESS";
export const SEARCH_GROUP_MEMBER_FAILED = "SEARCH_GROUP_MEMBER_FAILED";

export const GET_JOINED_GROUP_SUCCESS = "GET_JOINED_GROUP_SUCCESS";

export const GET_GROUP_MESSAGE_SUCCESS= "GET_GROUP_MESSAGE_SUCCESS";
export const GET_GROUP_MESSAGE_FAILED = "GET_GROUP_MESSAGE_FAILED";
export const GET_GROUP_MESSAGE_REQUEST = "GET_GROUP_MESSAGE_REQUEST";

export const GET_GROUP_ARTICLE_REQUEST ="GET_GROUP_ARTICLE_REQUEST";
export const GET_GROUP_ARTICLE_SUCCESS ="GET_GROUP_ARTICLE_SUCCESS";
export const GET_GROUP_ARTICLE_FAILED ="GET_GROUP_ARTICLE_FAILED";

export const POST_GROUP_ARTICLE_SUCCESS ="POST_GROUP_ARTICLE_SUCCESS";
export const GET_GROUP_UPDATED_ARTICLE = "GET_GROUP_UPDATED_ARTICLE"
export const DELETE_GROUP_ARTICLE ="DELETE_GROUP_ARTICLE";
export const GET_GROUP_ARTICLE_RESET ="GET_GROUP_ARTICLE_RESET";

export const GROUP_MEMBER_RESET = "GROUP_MEMBER_RESET"

export const GET_PUBLIC_DATA = "GET_PUBLIC_DATA";
export const RESET_PUBLIC_DATA = "RESET_PUBLIC_DATA";

