export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILED = "SIGN_UP_FAILED";

export const SIGN_IN_REQUEST = "SIGN_IN_REQUEST";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAILED = "SIGN_IN_FAILED";

export const UPDATE_USER = "UPDATE_USER";
export const LOGOUT = "LOGOUT";

export const SELECTED = "SELECTED";

export const GET_SELECTED_ARTICLE_REQUEST = "GET_SELECTED_ARTICLE_REQUEST";
export const GET_SELECTED_ARTICLE_SUCCESS = "GET_SELECTED_ARTICLE_SUCCESS";
export const GET_SELECTED_ARTICLE_FAILED = "GET_SELECTED_ARTICLE_FAILED";

export const CHANGE_SELECT_DATE = "CHANGE_SELECT_DATA";

export const POST_ARTICLE_REQUEST = "POST_ARTICLE_REQUEST";
export const POST_ARTICLE_SUCCESS = "POST_ARTICLE_SUCCESS";
export const POST_ARTICLE_FAILED = "POST_ARTICLE_FAILED";

export const GET_ARTICLE_THIS_MONTH_REQUEST = "GET_ARTICLE_THIS_MONTH_REQUEST";
export const GET_ARTICLE_THIS_MONTH_SUCCESS = "GET_ARTICLE_THIS_MONTH_SUCCESS";
export const GET_ARTICLE_THIS_MONTH_FAILED = "GET_ARTICLE_THIS_MONTH_FAILED";

export const SEARCH_REQUEST = "SEARCH_REQUEST";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAILED = "SEARCH_FAILED";

export const FRIEND_REQUEST_REQUEST = "FRIEND_REQUEST_REQUEST";
export const FRIEND_REQUEST_SUCCESS = "FRIEND_REQUEST_SUCCESS";
export const FRIEND_REQUEST_FAILED = "FRIEND_REQUEST_FAILED";

export const GET_ARTICLE_REQUEST = "GET_ARTICLE_REQUEST";
export const GET_ARTICLE_SUCCESS = "GET_ARTICLE_SUCCESS";
export const GET_ARTICLE_FAILED = "GET_ARTICLE_FAILED";